---
# Fake Service to drop-in replacement in tests
apiVersion: v1
kind: Service
metadata:
  # DNS would be like zookeeper.namespace.svc
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: client
    - port: 7000
      name: prometheus
  selector:
    clickhouse-keeper.altinity.com/chk: clickhouse-keeper
    clickhouse-keeper.altinity.com/ready: "yes"
---
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: clickhouse-keeper
spec:
  defaults:
    templates:
      podTemplate: default
  templates:
    podTemplates:
      - name: default
        spec:
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: IfNotPresent
              # IMPORTANT !!!
              # clickhouse-keeper:24.3.5.46 version can be changed with TESTS only!
              # DO NOT CHANGE THE VERSION !
              image: "clickhouse/clickhouse-keeper:24.3.5.46"
              volumeMounts:
                - name: default
                  mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  configuration:
    clusters:
      - name: "test-only"
        layout:
          replicasCount: 3
    settings:
      logger/level: "trace"
      logger/console: "true"
      listen_host: "0.0.0.0"
      keeper_server/storage_path: /var/lib/clickhouse
      keeper_server/tcp_port: "2181"
      keeper_server/four_letter_word_white_list: "*"
      keeper_server/coordination_settings/raft_logs_level: "information"
      keeper_server/raft_configuration/server/port: "9444"
      prometheus/endpoint: "/metrics"
      prometheus/port: "7000"
      prometheus/metrics: "true"
      prometheus/events: "true"
      prometheus/asynchronous_metrics: "true"
      prometheus/status_info: "false"
