---
# Fake Service to drop-in replacement in tests
apiVersion: v1
kind: Service
metadata:
  # DNS would be like zookeeper.namespace.svc
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: client
    - port: 7000
      name: prometheus
  selector:
    clickhouse-keeper.altinity.com/chk: clickhouse-keeper
    clickhouse-keeper.altinity.com/ready: "yes"
---
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: clickhouse-keeper
  labels:
    app: clickhouse-keeper
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume
      logVolumeClaimTemplate: log-volume
      podTemplate: latest-with-volume-mounts
  configuration:
    clusters:
      - name: "test-only"
        layout:
          replicasCount: 1
    settings:
      logger/level: "trace"
      logger/console: "true"
      listen_host: "0.0.0.0"
      http_control/port: 9182
      http_control/readiness/endpoint: /ready
      keeper_server/tcp_port: "2181"
      keeper_server/four_letter_word_white_list: "*"
      keeper_server/coordination_settings/raft_logs_level: "information"
      keeper_server/raft_configuration/server/port: "9444"
      prometheus/endpoint: "/metrics"
      prometheus/port: "7000"
      prometheus/metrics: "true"
      prometheus/events: "true"
      prometheus/asynchronous_metrics: "true"
      prometheus/status_info: "false"
  templates:
    podTemplates:
      - name: latest-with-volume-mounts
        spec:
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: Always
              image: "clickhouse/clickhouse-keeper:latest-alpine"
              volumeMounts:
                - name: data-volume
                  mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
      - name: data-volume
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      - name: log-volume
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
