---
# Fake Service to drop-in replacement in tests
apiVersion: v1
kind: Service
metadata:
  # DNS would be like zookeeper.namespace.svc
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: client
    - port: 7000
      name: prometheus
  selector:
    clickhouse-keeper.altinity.com/chk: clickhouse-keeper
    clickhouse-keeper.altinity.com/ready: "yes"
---
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: clickhouse-keeper
  labels:
    app: clickhouse-keeper
spec:
  defaults:
    templates:
      volumeClaimTemplate: data-volume
      podTemplate: latest-with-volume-mounts
  configuration:
    clusters:
      - name: "test-only"
        layout:
          replicasCount: 1
  templates:
    podTemplates:
      - name: latest-with-volume-mounts
        spec:
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: Always
              image: "clickhouse/clickhouse-keeper:latest-alpine"
    volumeClaimTemplates:
      - name: data-volume
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
