apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: "$GRAFANA_PROMETHEUS_DATASOURCE_NAME"
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  resyncPeriod: 24h
  datasource:
    name: "${GRAFANA_PROMETHEUS_DATASOURCE_NAME}"
    type: prometheus
    access: proxy
    url: "${PROMETHEUS_URL}"
    isDefault: true
    editable: false
    jsonData:
      tlsSkipVerify: true
      timeInterval: "5s"
