rule_files:
  - prometheus-alert-rules-clickhouse.yaml
evaluation_interval: 30s
tests:
  - name: ClickHouseMetricsExporterDown
    interval: 30s
    input_series:
      - series: 'up{app="clickhouse-operator", pod_name="clickhouse-operator-XXX"}'
        values: "0+0x10"
    alert_rule_test:
      - eval_time: 30s
        alertname: ClickHouseMetricsExporterDown
        exp_alerts:
          - exp_labels:
              severity: critical
              pod_name: clickhouse-operator-XXX
              app: clickhouse-operator
            exp_annotations:
              description: "`metrics-exporter` not sent data more than 1 minutes.\nPlease check instance status\n```kubectl logs -n  clickhouse-operator-XXX -c metrics-exporter -f```"
              identifier: "clickhouse-operator-XXX"
              summary: "metrics-exporter possible down"

