apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "secure-cluster-secret-01"
spec:
  configuration:
    clusters:
      - name: "auto"
        secret:
          auto: "True"
        layout:
          shardsCount: 2
          replicasCount: 2
