apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallationTemplate"
metadata:
  name: chit-02
  annotations:
    chit-02-annotation: chit-02-annotation-value
spec:
  templating:
    policy: "manual"
    chiSelector:
      target-chi-label-manual: target-chi-label-manual-value
